import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
<<<<<<< Updated upstream
import Navigation from "../components/navigation";
import { Inter as FontSans } from "next/font/google";
=======
>>>>>>> Stashed changes

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
<<<<<<< Updated upstream
    <div>
      <Navigation />
      <body className={inter.className}>{children}</body>
    </div>
=======
    <html lang="en">
      <body className={inter.className}>
        {children}
      </body>
    </html>
>>>>>>> Stashed changes
  );
}
