import Footer from "@/components/Footer";
import { AuthProvider } from "@/components/metamask/authContext";
import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          {children}
          <Footer />
        </body>
      </AuthProvider>
    </html>
  );
}
